name: 'Build and publish Docker Images to GitHub Container registry'
description: 'Supports custom Dockerfile name, tags, build context, etc. Could generate Docker tags based on git branches.'
inputs:
  github-token:
    description: 'GitHub token to push Docker image to GitHub Packages'
    default: ${{ github.token }}
  image-name:
    description: 'Docker Image name'
    required: true
  image-tag:
    description: 'Docker Image tag'
    default: "latest"
  extract-git-tag:
    description: 'Extract git-tag from repository'
    default: "false"
  dockerfile:
    description: 'Dockerfile name'
    default: "Dockerfile"
  build-context:
    description: 'Path to build context'
    default: "."
  pull-image:
    description: 'Pull the image before buiding it'
    default: "false"
  additional-image-tags:
    description: 'Multiple tags that will be attached to a built image'
    default: ""
  image-platform:
    description: 'Target image platform/platforms'
    default: ""
  custom-args:
    description: 'Any additional docker build arguments as a string'
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.image-name }}
    - ${{ inputs.image-tag }}
    - ${{ inputs.extract-git-tag }}
    - ${{ inputs.dockerfile }}
    - ${{ inputs.build-context}}
    - ${{ inputs.pull-image}}
    - ${{ inputs.additional-image-tags}}
    - ${{ inputs.image-platform}}
    - ${{ inputs.custom-args}}
branding:
  icon: 'box'
  color: 'blue'
